name: receptico
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  dio: ^5.7.0
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  talker_flutter: ^4.6.0
  talker_dio_logger: ^4.6.0
  talker_bloc_logger: ^4.6.0
  auto_route: ^9.2.2
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  intl_utils: ^2.8.7

flutter:
  assets:
    - asset/icon/static/google_logo.svg
    - asset/icon/static/logo.svg
    - asset/icon/static/apple_logo.svg

  uses-material-design: true
  fonts:
    - family: SFProText
      fonts:
        - asset: asset/font/SFProText-Regular.ttf
          weight: 400
        - asset: asset/font/SFProText-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  output-dir: lib/generated
