name: receptico
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  dio: ^5.7.0
  get_it: ^8.0.3
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  hive_flutter: ^1.1.0
  talker_flutter: ^4.6.4
  talker_dio_logger: ^4.6.4
  talker_bloc_logger: ^4.6.4
  auto_route: ^9.3.0
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  font_awesome_flutter: ^10.8.0
  cloud_firestore: ^5.6.1
  loading_animation_widget:
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.0
  hive_generator: ^2.0.1
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  intl_utils: ^2.8.7
  bloc_test: ^9.1.7
  mockito: ^5.4.5

flutter:
  assets:
    - asset/icon/static/google_logo.svg
    - asset/icon/static/logo.svg
    - asset/icon/static/apple_logo.svg
    - asset/icon/light_theme/subscribe_back.svg
    - asset/icon/light_theme/grape.svg
    - asset/icon/light_theme/arrow.svg
    - asset/icon/light_theme/bels.svg
    - asset/icon/light_theme/callback.svg
    - asset/icon/light_theme/error.svg
    - asset/icon/light_theme/FAQ.svg
    - asset/icon/light_theme/info.svg
    - asset/icon/light_theme/lang.svg
    - asset/icon/light_theme/logOut.svg
    - asset/icon/light_theme/question.svg
    - asset/icon/light_theme/recomend.svg
    - asset/icon/light_theme/star.svg
    - asset/icon/light_theme/sun.svg
    - asset/icon/light_theme/edit.svg
    - asset/icon/light_theme/icons-solid.svg
    - asset/icon/light_theme/icons_thin.svg

  uses-material-design: true
  fonts:
    - family: SFProText
      fonts:
        - asset: asset/font/SFProText-Regular.ttf
          weight: 400
        - asset: asset/font/SFProText-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
  arb-dir: lib/l10n
  output-dir: lib/generated
